- name: Download install script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp/script.deb.sh
    mode: u+rwx

- name: Install Gitlab
  shell: /tmp/script.deb.sh && apt install gitlab-ce && gitlab-ctl reconfigure

- name: Download repo config
  get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh
    dest: /tmp/runner_script.deb.sh
    mode: u+rwx

- name: Install runner
  shell: /tmp/runner_script.deb.sh && apt install gitlab-ci-multi-runner

